//! Pre-seeded skeleton for MIK-3025. Worker fills bodies.
//!
//! - AC.1: MIK-3025.AC.1 AC.1: Memo `docs/competitive/shamash-comparison.md` exists, records the architectural-layer finding for `shamash` (one of proxy / orchestrator / lifecycle-manager) under a `## Architectural layer` header, and states an explicit `**Verdict**:` line naming one of COMPETITOR / COMPLEMENT / COLLABORATION-VECTOR. CHECK: file `docs/competitive/shamash-comparison.md` matches regex `(?s)## Architectural layer.*\*\*Verdict\*\*:\s*(COMPETITOR|COMPLEMENT|COLLABORATION-VECTOR)` (expected: header present and verdict line names one enum value).
//! - AC.2: MIK-3025.AC.2 AC.2: Memo contains a comparison matrix covering all eight required axes as table rows: tool-poisoning detection, schema pinning, mTLS, message signing, BPD validation, audit chain, A2A support, transport types. CHECK: file `docs/competitive/shamash-comparison.md` contains each literal string (case-insensitive) `tool-poisoning`, `schema pinning`, `mTLS`, `message signing`, `BPD`, `audit`, `A2A`, `transport`.
//! - AC.3: MIK-3025.AC.3 AC.3: Memo documents the COMPLEMENT integration pattern (how gateway composes in front of a shamash-managed mesh) under `## Integration pattern`, and records the COLLABORATION-VECTOR follow-up. CHECK: file `docs/competitive/shamash-comparison.md` contains `## Integration pattern` AND matches regex `Follow-up:\s*(MIK-\d+|none required)`.
//! - AC.4: MIK-3025.AC.4 AC.4: Committed doc-validation test enforces memo completeness and fail-fasts on placeholder content. The test reads the memo via `repo_file`/`read_repo_file` (mirror `tests/public_claims_validation.rs`), asserts the AC.1/AC.2/AC.3 structure, and asserts the memo contains no `TODO`, `TBD`, `???`, or empty matrix cell (regex `\|\s*\|`). CHECK: `cargo test --test mik_3025_shamash_comparison` exits 0 (expected: all assertions pass; RED if any required section/axis is missing or a placeholder remains).
//! - AC.5: MIK-3025.AC.5 AC.5: Memo cites verifiable sources for both sides — the `shamash` repo URL/README and at least one `mcp-gateway` `src/` path grounding each gateway matrix value. CHECK: file `docs/competitive/shamash-comparison.md` contains `github.com/heath-hunnicutt-ruach-tov/shamash` AND matches regex `src/(mtls|attestation|capability|a2a)/`.
//! - AC.6: MIK-3025.AC.6 AC.deploy: Diff merged to `main` (memo + doc-validation test), release built and the `mik_3025_shamash_comparison` test green in CI on `main`; if the COLLABORATION-VECTOR is pursued, a follow-up Linear issue is filed and linked both ways before Done. CHECK: `git log origin/main --grep 'MIK-3025' --oneline` exits 0 AND `rg -l 'shamash-comparison' docs/ tests/` finds both the memo and the test.
//! - AC.7: AC.deploy: Diff merged to `main` (target main), release binary built and deployed by the cron, and 30 min of post-deploy telemetry confirms the change is active.

#[cfg(test)]
mod tests {}
