//! Pre-seeded skeleton for MIK-6573. Worker fills bodies.
//!
//! - AC.1: MIK-6573.AC.1 AC.1: Heartbeat is emitted from the public entrypoint `run_server` (`src/main.rs:431`) at most once per install per day — a `~/.mcp-gateway/telemetry/last_heartbeat` date guard skips the send when the stored date equals today — and the request targets the MIK-6565 collector (default const, overridable by `MCP_GATEWAY_TELEMETRY_URL`) carrying project id `"mcp-gateway"`. CHECK: `cargo test --test mik_6573_acs heartbeat_once_per_day` exits 0 AND file `src/telemetry/mod.rs` contains regex `"mcp-gateway"` and `last_heartbeat` and `MCP_GATEWAY_TELEMETRY_URL`.
//! - AC.2: MIK-6573.AC.2 AC.2: The serialized payload contains only `project`, `event`, `version`, `runtime`, and optional `install_id`, has no `ip`/host/path/internal field, and is `<= 2048` bytes. CHECK: `cargo test --test mik_6573_acs payload_minimal_no_ip_under_2kb` exits 0 (test asserts serialized bytes len ≤ 2048, no `"ip"` key, keys ⊆ the allowed set).
//! - AC.3: MIK-6573.AC.3 AC.3: Telemetry is suppressed (no network call) when any of `NO_TELEMETRY`, `DO_NOT_TRACK`, or project-native `MCP_GATEWAY_NO_TELEMETRY` is set, when config `telemetry.enabled = false`, when `CI` or `GITHUB_ACTIONS` is present, or in debug/test builds (`cfg!(debug_assertions)` / `cfg!(test)`); browser-surface DNT is honoured by the optional `webui` respecting the `DNT: 1` request header. CHECK: `cargo test --test mik_6573_acs opt_out_suppresses_all_channels` exits 0.
//! - AC.4: MIK-6573.AC.4 AC.4: Telemetry is failure-open and light — the send is bounded to one short async request with a `<= 3s` reqwest timeout, a timeout or any 4xx/5xx returns `Ok`/is swallowed and never blocks startup, and the change adds zero new crate dependencies. CHECK: `cargo test --test mik_6573_acs timeout_and_5xx_are_failure_open` exits 0 AND `git diff HEAD~1 -- Cargo.toml | rg -c '^\+[a-z]' ` prints `0` (no added dependency lines).
//! - AC.5: MIK-6573.AC.5 AC.5: Committed tests in `tests/mik_6573_acs.rs` cover the happy-path send against a mocked in-process collector (asserts the POST body), opt-out suppression, and timeout behaviour, and the project gates stay green. CHECK: `cargo test --all-features --test mik_6573_acs` exits 0 AND `cargo clippy --all-features -- -D warnings` exits 0.
//! - AC.6: MIK-6573.AC.6 AC.6: Public docs (README) gain a "Telemetry & Privacy" section stating exactly what is collected, every way to disable it, and that active-user geography is derived server-side in aggregate via MIK-6565 with k-anonymity ≥ 5. CHECK: file `README.md` matches regex `(?i)telemetry` AND contains both `NO_TELEMETRY` and `MIK-6565` and `k-anonymity`.
//! - AC.7: MIK-6573.AC.7 AC.deploy: Diff merged to `main` (target main), release binary built and deployed by the cron, and 30 min of post-deploy telemetry confirms the `mcp-gateway` heartbeat event is being received (active-user count > 0 on the MIK-6565 dashboard). CHECK: `git log origin/main --grep 'MIK-6573' --oneline` exits 0 AND the MIK-6565 collector shows project `mcp-gateway` heartbeats in production over the post-deploy window.

#[cfg(test)]
mod tests {}
