// SPDX-FileCopyrightText: 2026 Mikko Parkkola
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
//! MIK-3274.RANKING.3 -- baseline-and-freeze measurement.
//!
//! Runs the held-out corpus at `benchmarks/ranking-baseline/corpus.json`
//! (generated by `gen_corpus.py`, not authored by reading ranker behaviour)
//! through the *unmodified* production ranker (`mcp_gateway::ranking`) and
//! writes `benchmarks/ranking-baseline/results.json`.
//!
//! This test measures; it must never be edited to make the ranker look
//! better. `src/ranking/scoring.rs` and `src/ranking/mod.rs` are read-only
//! for this ticket.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use mcp_gateway::capability::CapabilityLoader;
use mcp_gateway::ranking::{SearchRanker, SearchResult};
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
// `corpus_size` mirrors the key in the frozen corpus.json and cannot be renamed.
#[allow(clippy::struct_field_names)]
struct Corpus {
    criterion: String,
    tool_inventory_size: usize,
    corpus_size: usize,
    cases: Vec<CorpusCase>,
}

#[derive(Deserialize)]
struct CorpusCase {
    id: String,
    query: String,
    derivation: String,
    gold_tools: Vec<String>,
}

#[derive(Serialize)]
struct CaseResult {
    id: String,
    derivation: String,
    query: String,
    gold_tools: Vec<String>,
    best_gold_rank: Option<usize>, // 1-indexed position of the best-ranked gold tool
    top1_hit: bool,
    top3_hit: bool,
    top5_hit: bool,
    reciprocal_rank: f64,
}

#[derive(Serialize)]
struct DerivationSummary {
    n: usize,
    top1_hit_rate: f64,
    top3_hit_rate: f64,
    mean_reciprocal_rank: f64,
}

#[derive(Serialize)]
struct Report {
    criterion: String,
    tool_inventory_size: usize,
    corpus_size: usize,
    candidate_pool_size: usize,
    overall_top1_hit_rate: f64,
    overall_top3_hit_rate: f64,
    overall_top5_hit_rate: f64,
    overall_mean_reciprocal_rank: f64,
    by_derivation: BTreeMap<String, DerivationSummary>,
    cases: Vec<CaseResult>,
}

/// Load the full production capability inventory (excludes `capabilities/examples/`,
/// matching `capabilities/README.md`'s stated 119-capability count).
async fn load_candidate_pool() -> Vec<(String, String)> {
    let cap_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("capabilities");
    let mut dirs: Vec<String> = Vec::new();
    for entry in fs::read_dir(&cap_root).expect("read capabilities/") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        if path.file_name().and_then(|n| n.to_str()) == Some("examples") {
            continue;
        }
        dirs.push(path.to_string_lossy().into_owned());
    }
    let dir_refs: Vec<&str> = dirs.iter().map(String::as_str).collect();
    let defs = CapabilityLoader::load_directories(&dir_refs)
        .await
        .expect("load production capability inventory");
    defs.into_iter().map(|d| (d.name, d.description)).collect()
}

fn rank_case(pool: &[(String, String)], ranker: &SearchRanker, case: &CorpusCase) -> CaseResult {
    let candidates: Vec<SearchResult> = pool
        .iter()
        .map(|(name, desc)| SearchResult::new("fulcrum", name.clone(), desc.clone()))
        .collect();
    let ordered = ranker.rank(candidates, &case.query);

    let best_gold_rank = case
        .gold_tools
        .iter()
        .filter_map(|gold| ordered.iter().position(|r| &r.tool == gold))
        .map(|pos0| pos0 + 1) // 1-indexed
        .min();

    #[allow(clippy::cast_precision_loss)] // rank is bounded by the candidate count, never near 2^52
    let reciprocal_rank = best_gold_rank.map_or(0.0, |r| 1.0 / r as f64);

    CaseResult {
        id: case.id.clone(),
        derivation: case.derivation.clone(),
        query: case.query.clone(),
        gold_tools: case.gold_tools.clone(),
        best_gold_rank,
        top1_hit: best_gold_rank == Some(1),
        top3_hit: best_gold_rank.is_some_and(|r| r <= 3),
        top5_hit: best_gold_rank.is_some_and(|r| r <= 5),
        reciprocal_rank,
    }
}

#[allow(clippy::cast_precision_loss)] // corpus case count is in the hundreds
fn mean(values: impl Iterator<Item = f64> + Clone) -> f64 {
    let count = values.clone().count();
    if count == 0 {
        return 0.0;
    }
    values.sum::<f64>() / count as f64
}

#[tokio::test]
async fn mik_3274_ranking_3_baseline() {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let corpus_path = repo_root.join("benchmarks/ranking-baseline/corpus.json");
    let corpus_raw = fs::read_to_string(&corpus_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", corpus_path.display()));
    let corpus: Corpus = serde_json::from_str(&corpus_raw).expect("parse corpus.json");
    assert_eq!(
        corpus.cases.len(),
        corpus.corpus_size,
        "corpus.json corpus_size field must match cases.len()"
    );

    let pool = load_candidate_pool().await;
    assert_eq!(
        pool.len(),
        corpus.tool_inventory_size,
        "candidate pool size drifted from the corpus's recorded tool_inventory_size \
         (capabilities/ changed since the corpus was generated -- regenerate it)"
    );

    // Fresh ranker, no usage history recorded: isolates pure text-relevance
    // behaviour, which is what step 1 established is the entire ranker today.
    let ranker = SearchRanker::new();

    let cases: Vec<CaseResult> = corpus
        .cases
        .iter()
        .map(|case| rank_case(&pool, &ranker, case))
        .collect();

    let mut by_derivation: BTreeMap<String, Vec<&CaseResult>> = BTreeMap::new();
    for c in &cases {
        by_derivation
            .entry(c.derivation.clone())
            .or_default()
            .push(c);
    }
    let by_derivation: BTreeMap<String, DerivationSummary> = by_derivation
        .into_iter()
        .map(|(k, v)| {
            let n = v.len();
            (
                k,
                DerivationSummary {
                    n,
                    top1_hit_rate: mean(v.iter().map(|c| f64::from(u8::from(c.top1_hit)))),
                    top3_hit_rate: mean(v.iter().map(|c| f64::from(u8::from(c.top3_hit)))),
                    mean_reciprocal_rank: mean(v.iter().map(|c| c.reciprocal_rank)),
                },
            )
        })
        .collect();

    let report = Report {
        criterion: corpus.criterion.clone(),
        tool_inventory_size: corpus.tool_inventory_size,
        corpus_size: corpus.corpus_size,
        candidate_pool_size: pool.len(),
        overall_top1_hit_rate: mean(cases.iter().map(|c| f64::from(u8::from(c.top1_hit)))),
        overall_top3_hit_rate: mean(cases.iter().map(|c| f64::from(u8::from(c.top3_hit)))),
        overall_top5_hit_rate: mean(cases.iter().map(|c| f64::from(u8::from(c.top5_hit)))),
        overall_mean_reciprocal_rank: mean(cases.iter().map(|c| c.reciprocal_rank)),
        by_derivation,
        cases,
    };

    let results_path = repo_root.join("benchmarks/ranking-baseline/results.json");
    let json = serde_json::to_string_pretty(&report).expect("serialize report");
    fs::write(&results_path, json + "\n")
        .unwrap_or_else(|e| panic!("write {}: {e}", results_path.display()));

    // Runnable sanity check: the report must be well-formed, not that the
    // ranker scores any particular way -- this test measures, it does not grade.
    assert_eq!(report.corpus_size, corpus.cases.len());
    assert!(report.overall_top1_hit_rate >= 0.0 && report.overall_top1_hit_rate <= 1.0);
    assert!(
        !report.by_derivation.is_empty(),
        "expected per-derivation breakdown to be populated"
    );
}
