// SPDX-FileCopyrightText: 2026 Mikko Parkkola
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
//! The curated entries behind `mcp-gateway add <name>`. Every entry is checked
//! live by `scripts/dev/check-registry-packages.py` (MIK-7787).

use super::{ARBITRARY_REACH_REASON, Auth, HttpFlavor, Reach, RegistryEntry, Setup, Transport};

pub(super) static REGISTRY: &[RegistryEntry] = &[
    // ── search ──────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "tavily",
        description: "Web search and content extraction via the Tavily AI search API",
        command: "npx -y tavily-mcp@0.2.22",
        required_env: &["TAVILY_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "search",
        homepage: "https://github.com/tavily-ai/tavily-mcp",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "brave-search",
        description: "Web, news, image and local search using the Brave Search API",
        command: "npx -y @brave/brave-search-mcp-server@2.1.4",
        required_env: &["BRAVE_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "search",
        homepage: "https://github.com/brave/brave-search-mcp-server",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "exa",
        description: "Neural web search and content crawling via Exa AI",
        command: "npx -y exa-mcp-server@3.4.1",
        required_env: &["EXA_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "search",
        homepage: "https://github.com/exa-labs/exa-mcp-server",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "perplexity",
        description: "AI-powered research search via Perplexity API",
        command: "npx -y @perplexity-ai/mcp-server@1.3.0",
        required_env: &["PERPLEXITY_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "search",
        homepage: "https://github.com/perplexityai/modelcontextprotocol",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── filesystem ──────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "filesystem",
        description: "Read, write, and navigate the local file system (append the allowed directories)",
        command: "npx -y @modelcontextprotocol/server-filesystem@2026.8.31",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "filesystem",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::NeedsArgs {
            hint: "the directories it may access",
        },
    },
    // ── database ────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "postgres",
        description: "Query, explain and tune PostgreSQL databases",
        command: "uvx postgres-mcp@0.3.0",
        required_env: &["DATABASE_URI"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "database",
        homepage: "https://github.com/crystaldba/postgres-mcp",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "a PostgreSQL server (DATABASE_URI)",
        },
    },
    RegistryEntry {
        name: "mysql",
        description: "Query MySQL and MariaDB databases",
        command: "npx -y @benborla29/mcp-server-mysql@2.0.9",
        required_env: &["MYSQL_HOST", "MYSQL_USER", "MYSQL_PASS", "MYSQL_DB"],
        optional_env: &["MYSQL_PORT"],
        transport: Transport::Stdio,
        category: "database",
        homepage: "https://github.com/benborla/mcp-server-mysql",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "a MySQL or MariaDB server",
        },
    },
    RegistryEntry {
        name: "redis",
        description: "Interact with Redis key-value stores",
        command: "uvx redis-mcp-server@0.5.1",
        required_env: &[],
        optional_env: &["REDIS_HOST", "REDIS_PORT", "REDIS_PWD", "REDIS_DB"],
        transport: Transport::Stdio,
        category: "database",
        homepage: "https://github.com/redis/mcp-redis",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "a Redis server (REDIS_HOST, default localhost)",
        },
    },
    // ── dev-tools ───────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "github",
        description: "GitHub repos, issues, PRs, code search, and Actions (GitHub-hosted)",
        command: "",
        required_env: &["GITHUB_TOKEN"],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://api.githubcopilot.com/mcp/",
            flavor: HttpFlavor::Streamable,
        },
        category: "dev-tools",
        homepage: "https://github.com/github/github-mcp-server",
        auth: Auth::Header {
            name: "Authorization",
            value: "Bearer ${GITHUB_TOKEN}",
        },
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "gitlab",
        description: "GitLab projects, issues, merge requests, and pipelines (GitLab-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://gitlab.com/api/v4/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "dev-tools",
        homepage: "https://docs.gitlab.com/user/gitlab_duo/model_context_protocol/mcp_server/",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "linear",
        description: "Linear issues, projects, and cycles (Linear-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.linear.app/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "dev-tools",
        homepage: "https://linear.app/docs/mcp",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "sentry",
        description: "Sentry issues, errors, and releases (Sentry-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.sentry.dev/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "dev-tools",
        homepage: "https://github.com/getsentry/sentry-mcp",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "atlassian",
        description: "Jira and Confluence issues, pages, and search (Atlassian-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.atlassian.com/v1/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "dev-tools",
        homepage: "https://github.com/atlassian/atlassian-mcp-server",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "asana",
        description: "Asana tasks, projects, and workspaces (Asana-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.asana.com/sse",
            flavor: HttpFlavor::Sse,
        },
        category: "dev-tools",
        homepage: "https://developers.asana.com/docs/using-asanas-mcp-server",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── cloud ───────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "aws",
        description: "AWS resource management through the AWS CLI command surface",
        command: "uvx awslabs.aws-api-mcp-server@1.5.6",
        required_env: &[],
        optional_env: &["AWS_PROFILE", "AWS_REGION"],
        transport: Transport::Stdio,
        category: "cloud",
        homepage: "https://github.com/awslabs/mcp/tree/main/src/aws-api-mcp-server",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "AWS credentials in ~/.aws (the default chain; AWS_PROFILE picks a profile)",
        },
    },
    RegistryEntry {
        name: "cloudflare-workers",
        description: "Cloudflare Workers bindings: KV, D1, R2, and Workers (Cloudflare-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://bindings.mcp.cloudflare.com/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "cloud",
        homepage: "https://github.com/cloudflare/mcp-server-cloudflare",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── memory ──────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "memory",
        description: "Persistent knowledge-graph memory for agents",
        command: "npx -y @modelcontextprotocol/server-memory@2026.8.31",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "memory",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── communication ───────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "slack",
        description: "Read channels, threads, and search Slack workspaces (community server)",
        command: "npx -y slack-mcp-server@1.3.0",
        required_env: &["SLACK_MCP_XOXP_TOKEN"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "communication",
        homepage: "https://github.com/korotovsky/slack-mcp-server",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── knowledge ───────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "context7",
        description: "Up-to-date library documentation via Context7 (HTTP)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.context7.com/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "knowledge",
        homepage: "https://context7.com",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "fetch",
        description: "Fetch any HTTP URL and return its contents as markdown",
        command: "uvx mcp-server-fetch@2026.8.18",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "knowledge",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
        auth: Auth::None,
        reach: Reach::Arbitrary {
            reason: ARBITRARY_REACH_REASON,
        },
        setup: Setup::Ready,
    },
    // ── code ────────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "sequential-thinking",
        description: "Structured multi-step reasoning and problem decomposition",
        command: "npx -y @modelcontextprotocol/server-sequential-thinking@2026.8.31",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "code",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "semgrep",
        description: "Static analysis and security scanning via Semgrep",
        command: "uvx semgrep-mcp@0.9.0",
        required_env: &[],
        optional_env: &["SEMGREP_APP_TOKEN"],
        transport: Transport::Stdio,
        category: "code",
        homepage: "https://github.com/semgrep/mcp",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "the Semgrep engine: first use downloads it (~100 MB)",
        },
    },
    RegistryEntry {
        name: "playwright",
        description: "Browser automation via Playwright: navigate, click, fill, and snapshot pages",
        command: "npx -y @playwright/mcp@0.0.83 --headless --isolated",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "code",
        homepage: "https://github.com/microsoft/playwright-mcp",
        auth: Auth::None,
        reach: Reach::Arbitrary {
            reason: ARBITRARY_REACH_REASON,
        },
        setup: Setup::Ready,
    },
    // ── productivity ────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "notion",
        description: "Read and write Notion pages and databases (Notion-hosted, OAuth)",
        command: "",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.notion.com/mcp",
            flavor: HttpFlavor::Streamable,
        },
        category: "productivity",
        homepage: "https://developers.notion.com/docs/mcp",
        auth: Auth::OAuth,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "airtable",
        description: "Query and update Airtable bases and tables (community server)",
        command: "npx -y airtable-mcp-server@1.14.0",
        required_env: &["AIRTABLE_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "productivity",
        homepage: "https://github.com/domdomegg/airtable-mcp-server",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── finance ─────────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "stripe",
        description: "Stripe payments, customers, invoices, and subscriptions (Stripe-hosted, restricted API key)",
        command: "",
        required_env: &["STRIPE_SECRET_KEY"],
        optional_env: &[],
        transport: Transport::Http {
            default_url: "https://mcp.stripe.com",
            flavor: HttpFlavor::Streamable,
        },
        category: "finance",
        homepage: "https://docs.stripe.com/mcp",
        auth: Auth::Header {
            name: "Authorization",
            value: "Bearer ${STRIPE_SECRET_KEY}",
        },
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── vector-db ───────────────────────────────────────────────────────────────────
    RegistryEntry {
        name: "pinecone",
        description: "Pinecone vector database: indexes, search, and documentation",
        command: "npx -y @pinecone-database/mcp@0.3.0",
        required_env: &["PINECONE_API_KEY"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "vector-db",
        homepage: "https://github.com/pinecone-io/pinecone-mcp",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "qdrant",
        description: "Qdrant vector search engine: store and find memories",
        command: "uvx mcp-server-qdrant@0.8.1",
        required_env: &["QDRANT_URL", "COLLECTION_NAME"],
        optional_env: &["QDRANT_API_KEY"],
        transport: Transport::Stdio,
        category: "vector-db",
        homepage: "https://github.com/qdrant/mcp-server-qdrant",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    // ── MIK-7787 additions (top-15 research, 2026-10-02) ─────────────────────────
    RegistryEntry {
        name: "time",
        description: "Current time and time-zone conversion",
        command: "uvx mcp-server-time@2026.8.18",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "utility",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
        auth: Auth::None,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "git",
        description: "Read and change a local git repository: status, diff, log, commit (append --repository <path>)",
        command: "uvx mcp-server-git@2026.8.18",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "dev-tools",
        homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
        auth: Auth::None,
        reach: Reach::Arbitrary {
            reason: "Without --repository it reads and commits to any repository path a tool call \
                 names, so a prompt injection can reach every repository you own. It is added \
                 disabled; append --repository <path> to its command, then set `enabled: true`.",
        },
        setup: Setup::NeedsArgs {
            hint: "--repository <path>; it can write commits there",
        },
    },
    RegistryEntry {
        name: "chrome-devtools",
        description: "Drive and debug Chrome through DevTools: navigate, inspect, trace performance",
        command: "npx -y chrome-devtools-mcp@1.10.1 --headless --isolated --no-usage-statistics --no-performance-crux",
        required_env: &[],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "code",
        homepage: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
        auth: Auth::None,
        reach: Reach::Arbitrary {
            reason: ARBITRARY_REACH_REASON,
        },
        setup: Setup::NeedsService {
            hint: "a local Chrome or Chromium install",
        },
    },
    RegistryEntry {
        name: "grafana",
        description: "Grafana dashboards, Prometheus and Loki queries, alerts, and incidents (read-only)",
        command: "uvx mcp-grafana@2.0.0 --disable-write",
        required_env: &["GRAFANA_URL", "GRAFANA_SERVICE_ACCOUNT_TOKEN"],
        optional_env: &["GRAFANA_ORG_ID"],
        transport: Transport::Stdio,
        category: "monitoring",
        homepage: "https://github.com/grafana/mcp-grafana",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "mongodb",
        description: "Query MongoDB databases and Atlas clusters (read-only; uses only the configured connection string)",
        command: "npx -y mongodb-mcp-server@3.0.5 --readOnly --disabledTools connect",
        required_env: &["MDB_MCP_CONNECTION_STRING"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "database",
        homepage: "https://github.com/mongodb-js/mongodb-mcp-server",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::NeedsService {
            hint: "a MongoDB server or Atlas cluster (MDB_MCP_CONNECTION_STRING)",
        },
    },
    RegistryEntry {
        name: "supabase",
        description: "Supabase projects, databases, and edge functions (read-only; personal access token)",
        command: "npx -y @supabase/mcp-server-supabase@0.13.0 --read-only",
        required_env: &["SUPABASE_ACCESS_TOKEN"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "database",
        homepage: "https://supabase.com/docs/guides/getting-started/mcp",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
    RegistryEntry {
        name: "hubspot",
        description: "HubSpot CRM contacts, companies, and deals (use a private app scoped read-only)",
        command: "npx -y @hubspot/mcp-server@0.4.0",
        required_env: &["PRIVATE_APP_ACCESS_TOKEN"],
        optional_env: &[],
        transport: Transport::Stdio,
        category: "crm",
        homepage: "https://developers.hubspot.com/mcp",
        auth: Auth::EnvVars,
        reach: Reach::Bounded,
        setup: Setup::Ready,
    },
];
