// SPDX-FileCopyrightText: 2026 Mikko Parkkola
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
//! SIGNING.4 deterministic MAC and independent ECMAScript verification tests.

use std::io::Write;
use std::process::{Command, Stdio};

use serde_json::{Value, json};

use super::MessageSigner;
use crate::protocol::{JsonRpcResponse, RequestId};

const KEY: &str = "independent-signing-test-key-0123456789abcdef";
const PREVIOUS: &str = "independent-previous-test-key-0123456789abcdef";
const TIMESTAMP: u64 = 1_700_000_000;

fn signer() -> MessageSigner {
    MessageSigner::new(KEY.as_bytes().to_vec(), None, "test-current".to_owned())
}

fn body() -> Value {
    json!({"content": [{"type": "text", "text": "hello"}], "isError": false})
}

fn response(id: Option<RequestId>, body: Value) -> JsonRpcResponse {
    let mut response = JsonRpcResponse::success(RequestId::Number(0), body);
    response.id = id;
    response
}

fn verify(
    response: &JsonRpcResponse,
    expected_id: Value,
    expected_nonce: Option<&str>,
    key: &str,
) -> std::result::Result<Value, String> {
    let script =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/common/signing_verifier.mjs");
    let input = json!({
        "wire": serde_json::to_string(response).expect("response wire JSON"),
        "options": {"key": key, "keyId": "test-current", "expectedId": expected_id,
            "expectedNonce": expected_nonce, "now": TIMESTAMP}
    });
    let mut child = Command::new("node")
        .arg(script)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("independent Node verifier must be installed; absence is a fixture failure");
    child
        .stdin
        .take()
        .expect("verifier stdin")
        .write_all(&serde_json::to_vec(&input).expect("verifier input"))
        .expect("write verifier input");
    let output = child.wait_with_output().expect("wait for verifier");
    if output.status.success() {
        Ok(serde_json::from_slice(&output.stdout).expect("verified object diagnostic"))
    } else {
        Err(String::from_utf8(output.stderr).expect("verifier error UTF8"))
    }
}

#[test]
fn signing_v2_fixed_vector_authenticates_the_exact_delivered_envelope() {
    let mut response = response(Some(RequestId::Number(1)), body());
    signer()
        .sign_json_rpc_response_at(&mut response, Some("test-nonce"), TIMESTAMP)
        .expect("sign valid vector");
    let result = response.result.as_ref().expect("result survives signing");
    // Handwritten canonical input, independently checked with Python HMAC and
    // Node in tests/common/signing_verifier.test.mjs, never generated by Rust.
    assert_eq!(
        result["_signature"]["sig"],
        "25108f07ec41691cd5db351e233d72a62b4dc49271ae79cfd2fb0d713c0d3fd0"
    );
    assert_eq!(result["_signature"]["version"], 2);
    assert_eq!(result["_signature"]["alg"], "hmac-sha256");
    assert_eq!(result["_signature"]["nonce"], "test-nonce");
    assert_eq!(result["_signature"]["ts"], TIMESTAMP);
    assert_eq!(result["_signature"]["key_id"], "test-current");
    let mut signature_members: Vec<_> = result["_signature"]
        .as_object()
        .unwrap()
        .keys()
        .map(String::as_str)
        .collect();
    signature_members.sort_unstable();
    assert_eq!(
        signature_members,
        ["alg", "key_id", "nonce", "sig", "ts", "version"]
    );
    let verified = verify(
        &response,
        json!({"kind": "number", "value": "1"}),
        Some("test-nonce"),
        KEY,
    )
    .expect("independent verifier must authenticate Rust output");
    assert_eq!(verified["result"]["content"], body()["content"]);
}

#[test]
fn signing_v2_typed_request_id_vectors_include_i64_extrema_and_null() {
    let mut mismatches = Vec::new();
    for (id, expected_id, expected_mac) in [
        (
            None,
            Value::Null,
            "6fca4467b943bf495e1e8eedf4e15bceb21a729bd5c02540356e0795a6f23e21",
        ),
        (
            Some(RequestId::String("1".to_owned())),
            json!({"kind": "string", "value": "1"}),
            "183ef29999c3c56b9ff3fd63bf3ea920b5474e3a1c97c87053adfa75b26fe771",
        ),
        (
            Some(RequestId::Number(1)),
            json!({"kind": "number", "value": "1"}),
            "25108f07ec41691cd5db351e233d72a62b4dc49271ae79cfd2fb0d713c0d3fd0",
        ),
        (
            Some(RequestId::Number(i64::MIN)),
            json!({"kind": "number", "value": "-9223372036854775808"}),
            "755d3de10b5f9555087c5ff79748be4917df1aa18c58bc32991b87a698a95ed1",
        ),
        (
            Some(RequestId::Number(i64::MAX)),
            json!({"kind": "number", "value": "9223372036854775807"}),
            "fb7a95d629f1d6d4a2de33ee3bd82343d8fb1080d9423441594e4964b4b3976e",
        ),
    ] {
        let mut response = response(id, body());
        signer()
            .sign_json_rpc_response_at(&mut response, Some("test-nonce"), TIMESTAMP)
            .expect("sign typed-ID vector");
        if response.result.as_ref().expect("result")["_signature"]["sig"] != expected_mac {
            mismatches.push(expected_id.clone());
        }
        if let Err(error) = verify(&response, expected_id.clone(), Some("test-nonce"), KEY) {
            mismatches.push(json!({"id": expected_id, "verification": error}));
        }
    }
    assert!(
        mismatches.is_empty(),
        "SIGNING.4 typed-ID vectors failed: {mismatches:?}"
    );
}

#[test]
fn signing_v2_jcs_unicode_fraction_and_exponent_vector_is_interoperable() {
    let body = json!({
        "nested": [{"z": "supplementary 😀", "a": "\u{000f}\n\\\""}],
        "דּ": 7, "😀": 6, "€": 5,
        "numbers": [333_333_333.333_333_3, 1e30, 4.5, 2e-3, 1e-27, -0.0,
            9_007_199_254_740_991_i64, -9_007_199_254_740_991_i64]
    });
    let expected_id = json!({"kind": "string", "value": "unicode-\u{200b}-id"});
    let mut response = response(
        Some(RequestId::String("unicode-\u{200b}-id".to_owned())),
        body.clone(),
    );
    signer()
        .sign_json_rpc_response_at(&mut response, Some("vector-🦀"), TIMESTAMP)
        .expect("sign JCS vector");
    assert_eq!(
        response.result.as_ref().expect("result")["_signature"]["sig"],
        "9deaafde7102ed0e4fb66513836842251c46035c009cca9c8a187625e5197f7f"
    );
    let verified = verify(&response, expected_id, Some("vector-🦀"), KEY)
        .expect("Node verifies Rust JCS output");
    assert_eq!(verified["result"]["nested"], body["nested"]);
}

#[test]
fn signing_v2_nonce_and_timestamp_each_change_the_mac() {
    let mut signatures = std::collections::BTreeSet::new();
    for (nonce, timestamp) in [
        (Some("nonce-a"), TIMESTAMP),
        (Some("nonce-b"), TIMESTAMP),
        (None, TIMESTAMP),
        (Some("nonce-a"), TIMESTAMP + 1),
    ] {
        let mut response = response(Some(RequestId::Number(1)), body());
        signer()
            .sign_json_rpc_response_at(&mut response, nonce, timestamp)
            .expect("sign metadata vector");
        assert_eq!(
            response.result.as_ref().unwrap()["_signature"]["ts"],
            timestamp
        );
        verify(&response, json!({"kind":"number","value":"1"}), nonce, KEY)
            .expect("independent verifier authenticates each nonce/timestamp row");
        signatures.insert(
            response.result.as_ref().expect("result")["_signature"]["sig"]
                .as_str()
                .expect("MAC")
                .to_owned(),
        );
    }
    assert_eq!(
        signatures.len(),
        4,
        "SIGNING.4 nonce and timestamp are authenticated, not merely echoed"
    );
}

#[test]
fn signing_v2_relabeling_fails_mac_after_expected_metadata_matches() {
    let mut response = response(Some(RequestId::Number(1)), body());
    signer()
        .sign_json_rpc_response_at(&mut response, Some("test-nonce"), TIMESTAMP)
        .expect("sign original");
    verify(
        &response,
        json!({"kind":"number", "value":"1"}),
        Some("test-nonce"),
        KEY,
    )
    .expect("original positive control");
    let mut forged_nonce = response.clone();
    forged_nonce.result.as_mut().expect("result")["_signature"]["nonce"] = json!("forged-nonce");
    assert!(
        verify(
            &forged_nonce,
            json!({"kind":"number", "value":"1"}),
            Some("forged-nonce"),
            KEY
        )
        .expect_err("nonce forgery refused")
        .contains("MAC mismatch")
    );
    response.id = Some(RequestId::String("1".to_owned()));
    assert!(
        verify(
            &response,
            json!({"kind":"string", "value":"1"}),
            Some("test-nonce"),
            KEY
        )
        .expect_err("typed-ID forgery refused")
        .contains("MAC mismatch")
    );
}

#[test]
fn signing_v2_replaces_top_level_signature_and_authenticates_nested_signature_data() {
    let mut payload = body();
    payload["_signature"] = json!({"sig": "stale-backend-signature"});
    payload["nested"] = json!({"_signature": {"sig": "backend-owned-text"}});
    let mut response = response(Some(RequestId::Number(1)), payload);
    signer()
        .sign_json_rpc_response_at(&mut response, Some("test-nonce"), TIMESTAMP)
        .expect("sign envelope");
    let verified = verify(
        &response,
        json!({"kind":"number", "value":"1"}),
        Some("test-nonce"),
        KEY,
    )
    .expect("new top-level signature verifies");
    assert_eq!(
        verified["result"]["nested"]["_signature"]["sig"],
        "backend-owned-text"
    );
    response.result.as_mut().expect("result")["nested"]["_signature"]["sig"] = json!("tampered");
    assert!(
        verify(
            &response,
            json!({"kind":"number", "value":"1"}),
            Some("test-nonce"),
            KEY
        )
        .expect_err("nested signature is authenticated body data")
        .contains("MAC mismatch")
    );
}

#[test]
fn signing_v2_non_object_results_refuse_instead_of_silent_unsigned_success() {
    let mut accepted = Vec::new();
    for body in [
        Value::Null,
        json!("scalar"),
        json!([]),
        json!(17),
        json!(false),
        json!(true),
    ] {
        let mut response = response(Some(RequestId::Number(1)), body.clone());
        if signer()
            .sign_json_rpc_response_at(&mut response, None, TIMESTAMP)
            .is_ok()
        {
            accepted.push(body);
        }
    }
    assert!(
        accepted.is_empty(),
        "SIGNING.3 non-object final results were silently accepted: {accepted:?}"
    );
}

#[test]
fn signing_v2_exact_unsafe_body_integers_refuse_but_safe_boundaries_work() {
    for value in [9_007_199_254_740_991_i64, -9_007_199_254_740_991_i64] {
        for body in [
            json!({"value": value}),
            json!({"nested":{"value":value}}),
            json!({"nested":[[value]]}),
        ] {
            let mut response = response(Some(RequestId::Number(1)), body);
            signer()
                .sign_json_rpc_response_at(&mut response, None, TIMESTAMP)
                .expect("safe integer boundary at every container depth");
        }
    }
    let mut accepted = Vec::new();
    for value in [
        json!(9_007_199_254_740_992_i64),
        json!(-9_007_199_254_740_992_i64),
        json!(u64::MAX),
    ] {
        for body in [
            json!({"value":value}),
            json!({"nested":{"value":value}}),
            json!({"nested":[[value]]}),
        ] {
            let mut response = response(Some(RequestId::Number(1)), body.clone());
            if signer()
                .sign_json_rpc_response_at(&mut response, None, TIMESTAMP)
                .is_ok()
            {
                accepted.push(body);
            }
        }
    }
    assert!(
        accepted.is_empty(),
        "SIGNING.4 unsafe exact integers would lose precision: {accepted:?}"
    );
}

#[test]
fn signing_v2_current_key_signs_and_previous_key_does_not_verify() {
    let signer = MessageSigner::new(
        KEY.as_bytes().to_vec(),
        Some(PREVIOUS.as_bytes().to_vec()),
        "test-current".to_owned(),
    );
    let mut response = response(Some(RequestId::Number(1)), body());
    signer
        .sign_json_rpc_response_at(&mut response, None, TIMESTAMP)
        .expect("sign under current key");
    verify(&response, json!({"kind":"number", "value":"1"}), None, KEY)
        .expect("current key verifies");
    assert!(
        verify(
            &response,
            json!({"kind":"number", "value":"1"}),
            None,
            PREVIOUS
        )
        .expect_err("previous key must not verify current sender output")
        .contains("MAC mismatch")
    );
}

#[test]
fn signing_v2_protocol_error_remains_unsigned() {
    let mut response =
        JsonRpcResponse::error(Some(RequestId::Number(1)), -32601, "test method missing");
    let before = serde_json::to_value(&response).expect("error snapshot");
    signer()
        .sign_json_rpc_response_at(&mut response, Some("test-nonce"), TIMESTAMP)
        .expect("unsigned error no-op");
    assert_eq!(serde_json::to_value(response).expect("error wire"), before);
}

#[test]
fn signing_v2_absent_result_skips_defensive_nonce_validation() {
    let mut response = response(Some(RequestId::String("no-result".into())), body());
    response.result = None;
    assert!(response.error.is_none());
    let before = serde_json::to_value(&response).unwrap();
    signer()
        .sign_json_rpc_response_at(&mut response, Some(""), TIMESTAMP)
        .expect("no-result envelope is an unsigned no-op even with a defensive invalid nonce");
    assert_eq!(serde_json::to_value(response).unwrap(), before);
}

#[test]
fn signing_v2_defensive_nonce_byte_bounds_reject_without_signing() {
    for nonce in [String::new(), "x".repeat(257), "🦀".repeat(65)] {
        let mut response = response(Some(RequestId::Number(1)), body());
        let before = serde_json::to_value(&response).unwrap();
        signer()
            .sign_json_rpc_response_at(&mut response, Some(&nonce), TIMESTAMP)
            .expect_err("empty or over-256-byte nonce cannot be authenticated");
        assert_eq!(serde_json::to_value(response).unwrap(), before);
    }
}

#[test]
fn signing_v2_defensive_nonce_exact_byte_boundaries_verify() {
    for nonce in ["x".to_owned(), "x".repeat(256), "🦀".repeat(64)] {
        assert!((1..=256).contains(&nonce.len()));
        let mut response = response(Some(RequestId::Number(1)), body());
        signer()
            .sign_json_rpc_response_at(&mut response, Some(&nonce), TIMESTAMP)
            .expect("valid nonce byte boundary");
        verify(
            &response,
            json!({"kind":"number","value":"1"}),
            Some(&nonce),
            KEY,
        )
        .expect("exact boundary nonce must independently authenticate");
    }
}
